name: Continuous Benchmark

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: benchmark

      - name: Checkout Rinegine
        uses: actions/checkout@v4
        with:
          repository: maxsimilian560/Rinegine
          ref: wip
          path: Rinegine
          token: ${{ secrets.benchmark_token }}

      - name: Install deps
        run: |
          sudo apt-get update && sudo apt-get install -y cmake g++ libboost-dev libbenchmark-dev python3
          git clone --depth 1 https://github.com/electronicarts/EASTL.git ../EASTL
          ls -la ../EASTL/include/
          ln -sf eastl ../EASTL/include/EASTL
          ls -la ../EASTL/include/
          file ../EASTL/include/EASTL
          test -f ../EASTL/include/EASTL/list.h && echo "FOUND" || echo "NOT FOUND"
      - name: Debug
        run: 
          echo "=== EASTL include ===" && ls -R ../EASTL/include/
          echo "=== Symlink ===" && ls -la ../EASTL/include/EASTL
          echo "=== Test list.h ===" && ls ../EASTL/include/EASTL/list.h 2>&1 || echo "NOT FOUND"
      - name: Build
        working-directory: benchmark
        run: |
          g++ -O3 -march=native -std=c++23 -Wall -Wextra -I../Rinegine -I../EASTL/include -I/usr/include benchmark.cpp -L../Rinegine -L/usr/lib -lrg-kernel -lbenchmark_main -lbenchmark -lpthread -o benchmark_runner

      - name: Run benchmarks
        working-directory: benchmark
        run: sh ./run_bench.sh && sh ./update_result.sh

      # - name: Generate chart + table
      #   working-directory: benchmark
      #   run: python3 gen_chart.py benchmark_result.json RESULTS.md chart.svg && python3 gen_chart.py benchmark_result2.json RESULTS2.md chart2.svg

      - name: Commit results
        working-directory: benchmark
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add chart.svg RESULTS.md README.md
          git diff --cached --quiet || git commit -m "chore: update benchmark results [skip ci]"
          git push
